/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { YKSSigorta } from "./YKSSigorta";
export * as factories from "./factories";
export { YKSSigorta__factory } from "./factories/YKSSigorta__factory";
