/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface YKSSigortaInterface extends Interface {
  getFunction(
    nameOrSignature: "checkInsurance" | "examDate" | "mintPolicy" | "policies"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkInsurance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "examDate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkInsurance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "examDate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
}

export interface YKSSigorta extends BaseContract {
  connect(runner?: ContractRunner | null): YKSSigorta;
  waitForDeployment(): Promise<this>;

  interface: YKSSigortaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkInsurance: TypedContractMethod<
    [student: AddressLike],
    [boolean],
    "view"
  >;

  examDate: TypedContractMethod<[], [bigint], "view">;

  mintPolicy: TypedContractMethod<[student: AddressLike], [void], "nonpayable">;

  policies: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkInsurance"
  ): TypedContractMethod<[student: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "examDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintPolicy"
  ): TypedContractMethod<[student: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  filters: {};
}
